<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="prefix num theta">
        <joint name="${prefix}wheel${num}_shaft_joint" type="fixed">
            <origin xyz="${base_radius*cos(theta)} ${base_radius*sin(theta)} ${robot_height}" rpy="0.0 ${PI/2} ${theta+PI}"/>
            <parent link="${prefix}base_link"/>
            <child link="${prefix}wheel${num}_shaft_link"/>
            <axis xyz="${base_radius} 0.0 0.0"/>
        </joint>

        <link name="${prefix}wheel${num}_shaft_link">
            <visual>
                <origin xyz="0.0 0.0 -${distance_to_chassis/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_shaft_radius}" length="${distance_to_chassis}"/>
                </geometry>
            </visual>
        </link>

        <joint name="${prefix}wheel${num}_joint" type="continuous">
            <origin xyz="0.0 0.0 -${distance_to_chassis}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}wheel${num}_shaft_link"/>
            <child link="${prefix}wheel${num}_link"/>
            <axis xyz="0.0 0.0 1.0"/>
        </joint>

        <link name="${prefix}wheel${num}_link">
            <visual>
                <origin xyz="0.0 0.0 -${wheel_thickness/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </visual>
        </link>
    </xacro:macro>
</robot>
